name: Manual Sync & Init

on:
  workflow_dispatch:
    inputs:
      RESET_MODE:
        description: '⚠️ README 파일을 초기화하고 다시 만들까요?'
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run Update Script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          # 이 줄이 체크박스 값을 파이썬으로 던져주는 생명줄입니다.
          RESET_MODE: ${{ github.event.inputs.RESET_MODE }}
          FETCH_MODE: "ALL"
        run: python update_readme.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "docs: force update and reset" || exit 0
          git push
